# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Kirchgemeindebund Wilsdruff-Freital
owner: Ev.-Luth. Kirchgemeindebund Wilsdruff-Freital
description: ""

header-image: "/assets/img/churches/st_nikolaikirche_wilsdruff.jpg"

contact:
  name: Matthias Weinhold
  email: kgb.wilsdruff-freital@evlks.de
  phone: '+4935204 48286'
  fax: '+4935204 48236'
  street_address: Kirchplatz 3
  city: 01723 Wilsdruff

churches:
  title: "Kirchgemeinden"
  text: #"Lorem ipsum dolor sit amet consectetur."
  section: churches
  closebutton: "Schlie√üen"
  
collections:
  churches:

google_verify: ['TvUyDDIB758IKtWR0t3cS3S89ivZ8V034szemF2l69g']

permalink: pretty

sass:
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  
markdown: kramdown

exclude:
- "*.gemspec"
- LICENSE.txt
- README.md 
